### ISSUE TITLE
Path to model not working

### ISSUE THREAD

**Issue by romilchaudhary** [linto-ai/pyrtstools#2]
Hi Team,
Is there default model which I can give in ******kws = rts.kws.KWS("/path/to/your-model") # Hotword spotting******
I ma getting this error while trying to set kws = rts.kws.KWS("https://github.com/linto-ai/linto-models")
****

Traceback (most recent call last):                                                                                        File "test.py", line 11, in <module>                                                                                      kws = rts.kws.KWS("https://github.com/linto-ai/linto-models") # Hotword spotting                                      File "C:\pyrtstools\pyrtstools\kws\kws.py", line 72, in __init__                                                          self._inferer = Inferer(model_path)                                                                                   File "C:\pyrtstools\pyrtstools\kws\_inferer.py", line 9, in __init__                                                      assert model_path.split('.')[-1] in ['pb', 'net','hdf5', 'tflite'], "Supported mode files are .pb, .net and .tflite"                                                                                                                        AssertionError: Supported mode files are .pb, .net and .tflite

**Comment by Lokhozt** [comment]
Hello, 
The path must be a local path.
