### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute '_make_predict_function'

### ISSUE THREAD

**Issue by tjiho** [linto-ai/pyrtstools#4]
Hi ! 

I trained my model with the last version of `linto-desktoptools-hmg`.

When running `linto-command-module` with `python 3.6` and `tensorflow==2.4.1`, I have this Traceback:

```
Traceback (most recent call last):
  File "command.py", line 245, in <module>
    command = Command()
  File "command.py", line 61, in __init__
    self._kws = rts.kws.KWS(model_path, threshold=float(self.config['KWS_TH']), n_act_recquire=int(self.config['KWS_NACT']))
  File "/home/tjiho/info/linto-command-module/env/lib64/python3.6/site-packages/pyrtstools/kws/kws.py", line 72, in __init__
    self._inferer = Inferer(model_path)
  File "/home/tjiho/info/linto-command-module/env/lib64/python3.6/site-packages/pyrtstools/kws/_inferer.py", line 11, in __init__
    self._predict_fun = self._load_keras_model(model_path)
  File "/home/tjiho/info/linto-command-module/env/lib64/python3.6/site-packages/pyrtstools/kws/_inferer.py", line 21, in _load_keras_model
    self.model._make_predict_function()
AttributeError: 'Sequential' object has no attribute '_make_predict_function'
```

**Comment by Lokhozt** [comment]
Hello,
_make_predict_function seems to be depreciated since Keras has been incorporated to tensorflow. I haven't noticed it because Keras models (.hdf5) are not used in production.

I would advise you to use a TFLite model for PyRTSTools.
